// Code generated by Kitex v0.12.2. DO NOT EDIT.

package configservice

import (
	config "config_service/kitex_gen/config"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetConfig(ctx context.Context, req *config.GetConfigRequest, callOptions ...callopt.Option) (r *config.GetConfigResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kConfigServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConfigServiceClient struct {
	*kClient
}

func (p *kConfigServiceClient) GetConfig(ctx context.Context, req *config.GetConfigRequest, callOptions ...callopt.Option) (r *config.GetConfigResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConfig(ctx, req)
}
