// Code generated by Kitex v0.12.2. DO NOT EDIT.

package configservice

import (
	config "config_service/kitex_gen/config"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"getConfig": kitex.NewMethodInfo(
		getConfigHandler,
		newConfigServiceGetConfigArgs,
		newConfigServiceGetConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	configServiceServiceInfo                = NewServiceInfo()
	configServiceServiceInfoForClient       = NewServiceInfoForClient()
	configServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return configServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return configServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return configServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ConfigService"
	handlerType := (*config.ConfigService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "config",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.2",
		Extra:           extra,
	}
	return svcInfo
}

func getConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*config.ConfigServiceGetConfigArgs)
	realResult := result.(*config.ConfigServiceGetConfigResult)
	success, err := handler.(config.ConfigService).GetConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newConfigServiceGetConfigArgs() interface{} {
	return config.NewConfigServiceGetConfigArgs()
}

func newConfigServiceGetConfigResult() interface{} {
	return config.NewConfigServiceGetConfigResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetConfig(ctx context.Context, req *config.GetConfigRequest) (r *config.GetConfigResponse, err error) {
	var _args config.ConfigServiceGetConfigArgs
	_args.Req = req
	var _result config.ConfigServiceGetConfigResult
	if err = p.c.Call(ctx, "getConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
